package com.tipgame.ui.Tipp;

import java.util.List;

import org.hibernate.Session;
import org.vaadin.artur.icepush.ICEPush;

import com.tipgame.data.GameMatch;
import com.tipgame.data.User;
import com.tipgame.data.UserMatchConnection;
import com.tipgame.database.DatabaseHelper;
import com.tipgame.utils.TipgameUtils;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Runo;

public class TippView extends CustomComponent {

	private static final long serialVersionUID = -3251458515243143780L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	private VerticalLayout tippLayout;
	private User user;
	private List<UserMatchConnection> data;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public TippView(List<UserMatchConnection> data, User user) {
		this.user = user;
		this.data = data;

		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		createMatchViewOnTippViewLayout();
	}
	
	private void createMatchViewOnTippViewLayout()
	{
		String group = "";
		int viewOnLayoutIndex = 0;
		for (int i = 0; i < data.size(); i++) {
			GameMatch gameMatch = TipgameUtils.getGameMatchFromId(data.get(i));
			Session session = DatabaseHelper.getInstance().getHibernateSession();
			session.beginTransaction();
			DatabaseHelper.getInstance().attachPojoToSession(session, gameMatch);
			String gameMatchGroup = gameMatch.getGroup(); 
			if (!group.equalsIgnoreCase(gameMatchGroup))
			{
				Label groupLabel = new Label("Gruppe "+gameMatch.getGroup()+" : ");
				groupLabel.setStyleName(Runo.LABEL_H1);
				tippLayout.addComponent(groupLabel);
				group = gameMatch.getGroup();
				viewOnLayoutIndex++;
			}
			UserMatchConnection match = data.get(i);
			MatchView matchView = new MatchView(match, user);
			tippLayout.addComponent(matchView, viewOnLayoutIndex);
			viewOnLayoutIndex++;
		}
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		TabSheet tippTab = new TabSheet();
		tippTab.setWidth("100%");
		tippTab.setHeight("100%");
		tippTab.setStyleName(Runo.TABSHEET_SMALL);
		mainLayout.addComponent(tippTab);
		
		Panel MatchViewsPanel = new Panel();
		MatchViewsPanel.setImmediate(false);
		MatchViewsPanel.setWidth("100%");
		MatchViewsPanel.setHeight("100%");
		MatchViewsPanel.setScrollable(true);
		
		tippLayout = new VerticalLayout();
		tippLayout.setImmediate(false);
		tippLayout.setWidth("100%");
		tippLayout.setHeight("100%");
		tippLayout.setMargin(false);
		
		MatchViewsPanel.addComponent(tippLayout);
		tippTab.addTab(MatchViewsPanel, "Tipps Vorrunde");
		
		AdditionalTippsView additionalTippsView = new AdditionalTippsView(user);
		additionalTippsView.setImmediate(false);
		additionalTippsView.setWidth("100.0%");
		additionalTippsView.setHeight("100.0%");
		tippTab.addTab(additionalTippsView, "Zusätzliche Tipps");
		
		return mainLayout;
	}
}
