package com.tipgame.ui.Tipp;

import java.util.List;

import com.tipgame.data.User;
import com.tipgame.data.UserMatchConnection;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Runo;

public class TippView extends CustomComponent {

	private static final long serialVersionUID = -3251458515243143780L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	private VerticalLayout tippLayout;
	private TabSheet basicTippTabSheet;
	private TabSheet additionalTippTabSheet;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public TippView(List<UserMatchConnection> data, User user) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		createMatchViewOnTippViewLayout(data, user);
	}
	
	private void createMatchViewOnTippViewLayout(List<UserMatchConnection> data, User user)
	{
		for (int i = 0; i < data.size(); i++) {
			UserMatchConnection match = data.get(i);
			tippLayout.addComponent(new MatchView(match, user), i);
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		TabSheet tippTab = new TabSheet();
		tippTab.setWidth("100%");
		tippTab.setHeight("100%");
		mainLayout.addComponent(tippTab);
		
		basicTippTabSheet = new TabSheet();
		basicTippTabSheet.setImmediate(false);
		basicTippTabSheet.setWidth("100.0%");
		basicTippTabSheet.setHeight("100.0%");
		basicTippTabSheet.setStyleName(Runo.TABSHEET_SMALL);
		//mainLayout.addComponent(basicTippTabSheet);
		tippTab.addTab(basicTippTabSheet, "Tipp abgeben");
		
		additionalTippTabSheet = new TabSheet();
		additionalTippTabSheet.setImmediate(false);
		additionalTippTabSheet.setWidth("100.0%");
		additionalTippTabSheet.setHeight("100.0%");
		additionalTippTabSheet.setCaption("Zusätzliche Tipps");
		additionalTippTabSheet.setStyleName(Runo.TABSHEET_SMALL);
		//mainLayout.addComponent(additionalTippTabSheet);
		tippTab.addTab(additionalTippTabSheet, "Zusätzliche Tipps");
		
		AdditionalTippsView additionalTippsView = new AdditionalTippsView();
		additionalTippsView.setImmediate(false);
		additionalTippsView.setWidth("100.0%");
		additionalTippsView.setHeight("100.0%");
		additionalTippTabSheet.addComponent(additionalTippsView);
		
		Panel MatchViewsPanel = new Panel();
		MatchViewsPanel.setImmediate(false);
		MatchViewsPanel.setWidth("100%");
		MatchViewsPanel.setHeight("100%");
		MatchViewsPanel.setScrollable(true);
		
		tippLayout = new VerticalLayout();
		tippLayout.setImmediate(false);
		tippLayout.setWidth("100%");
		tippLayout.setHeight("100%");
		tippLayout.setMargin(false);
		
		MatchViewsPanel.addComponent(tippLayout);
		
		basicTippTabSheet.addComponent(MatchViewsPanel);
		
		return mainLayout;
	}

}
