package com.tipgame.Administration;

import java.util.Calendar;

import org.hibernate.Session;

import com.tipgame.data.News;
import com.tipgame.database.DatabaseHelper;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class NewsAdministrationView extends CustomComponent {

	private static final long serialVersionUID = -4657600132024928871L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button btnSaveNews;
	@AutoGenerated
	private TextArea newsTextArea;
	@AutoGenerated
	private Panel mainPanel;
	@AutoGenerated
	private VerticalLayout verticalLayoutOnPanel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public NewsAdministrationView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void onSaveButtonClick(Button.ClickEvent event)
	{
		DatabaseHelper databaseHelper = DatabaseHelper.getInstance();
		Session session = databaseHelper.getHibernateSession();
		session.beginTransaction();
		String newsText = (String)newsTextArea.getValue();
		News news = new News();
		Calendar cal = Calendar.getInstance();
		news.setTimestamp(cal.getTime());
		news.setMessage(newsText);
		session.save(news);
		session.getTransaction().commit();
	}
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// common part: create layout
		mainPanel = new Panel();
		mainPanel.setImmediate(false);
		mainPanel.setSizeFull();
		mainPanel.setScrollable(true);
				
		// verticalLayoutOnPanel
		verticalLayoutOnPanel = new VerticalLayout();
		verticalLayoutOnPanel.setImmediate(false);
		verticalLayoutOnPanel.setWidth("100.0%");
		verticalLayoutOnPanel.setHeight("100.0%");
		verticalLayoutOnPanel.setMargin(false);
		mainPanel.addComponent(verticalLayoutOnPanel);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// richTextArea_1
		newsTextArea = new TextArea();
		newsTextArea.setImmediate(false);
		newsTextArea.setWidth("582px");
		newsTextArea.setHeight("262px");
		verticalLayoutOnPanel.addComponent(newsTextArea);
		
		// btnSaveNews
		btnSaveNews = new Button("",this,"onSaveButtonClick");
		btnSaveNews.setCaption("Speichern");
		btnSaveNews.setImmediate(false);
		btnSaveNews.setWidth("-1px");
		btnSaveNews.setHeight("-1px");
		verticalLayoutOnPanel.addComponent(btnSaveNews);
		
		mainLayout.addComponent(mainPanel);
		
		return mainLayout;
	}

}
