package com.tipgame.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class AwayTeamView extends CustomComponent {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Label LabelAwayTeamName;
	@AutoGenerated
	private Embedded AwayTeamImage;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 7450939758364436744L;
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public AwayTeamView(String teamName, String imageSource) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		setAwayTeamView(teamName, imageSource);
	}

	private void setAwayTeamView(String teamName, String imageSource)
	{
		LabelAwayTeamName.setValue(teamName);
		
		AwayTeamImage = new Embedded();
		AwayTeamImage.setImmediate(false);
		AwayTeamImage.setWidth("40px");
		AwayTeamImage.setHeight("40px");
		AwayTeamImage.setSource(new ThemeResource(imageSource));
		AwayTeamImage.setType(1);
		AwayTeamImage.setMimeType("image/png");
		mainLayout.addComponent(AwayTeamImage, 0, 0);
		mainLayout.setComponentAlignment(AwayTeamImage, new Alignment(48));
	}
	
	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("140px");
		mainLayout.setHeight("40px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(2);
		
		// top-level component properties
		setWidth("140px");
		setHeight("40px");
		
		// LabelAwayTeamName
		LabelAwayTeamName = new Label();
		LabelAwayTeamName.setImmediate(false);
		LabelAwayTeamName.setWidth("-1px");
		LabelAwayTeamName.setHeight("-1px");
		LabelAwayTeamName.setValue("Auswärtsteam");
		mainLayout.addComponent(LabelAwayTeamName, 1, 0);
		mainLayout.setComponentAlignment(LabelAwayTeamName, new Alignment(33));
		
		return mainLayout;
	}

}
