package com.tipgame.ui;

import java.awt.Image;
import java.io.File;

import com.tipgame.data.GameMatch;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class FixtureView extends CustomComponent {

	private static final long serialVersionUID = 7537472284099370094L;
	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Label LabelVS;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public FixtureView(GameMatch match) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		setHomeTeamView(match.getHomeTeamName(), match.getHomeTeamImage());
		setAwayTeamView(match.getAwayTeamName(), match.getAwayTeamImage());		
	}
	
	private void setHomeTeamView(String teamName, String imageResource)
	{
		HomeTeamView homeTeamView = new HomeTeamView(teamName, imageResource);
		mainLayout.addComponent(homeTeamView, 0, 0);
	}
	
	private void setAwayTeamView(String teamName, String imageResource)
	{
		AwayTeamView homeTeamView = new AwayTeamView(teamName, imageResource);
		mainLayout.addComponent(homeTeamView, 0, 2);
	}
	
	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("420px");
		mainLayout.setHeight("41px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(3);
		
		// top-level component properties
		setWidth("420px");
		setHeight("41px");
		
		// LabelVS
		LabelVS = new Label();
		LabelVS.setImmediate(false);
		LabelVS.setWidth("-1px");
		LabelVS.setHeight("-1px");
		LabelVS.setValue(":");
		mainLayout.addComponent(LabelVS, 1, 0);
		mainLayout.setComponentAlignment(LabelVS, new Alignment(48));
		
		return mainLayout;
	}

}
