package com.tipgame.ui;

import java.awt.Image;
import java.io.File;

import com.tipgame.data.Match;
import com.tipgame.data.Team;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class FixtureView extends CustomComponent {

	private static final long serialVersionUID = 7537472284099370094L;
	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Label LabelVS;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public FixtureView(Match match) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		setHomeTeamView(match.getHomeTeamId(), 0);
		setAwayTeamView(match.getAwayTeamId(), 2);		
	}
	
	private void setHomeTeamView(int teamId, int column)
	{
		Team team = getTeam(teamId);
		HomeTeamView teamView = new HomeTeamView(team);
		mainLayout.addComponent(teamView, column, 0);
	}
	
	private void setAwayTeamView(int teamId, int column)
	{
		Team team = getTeam(teamId);
		AwayTeamView teamView = new AwayTeamView(team);
		mainLayout.addComponent(teamView, column, 0);
	}
	
	private Team getTeam(int teamId)
	{
		Team team = new Team();
		team.setTeamName("Deutschland");
		team.setImageFlag("resources/germany.jpg");
		
		return team;
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("420px");
		mainLayout.setHeight("41px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(3);
		
		// top-level component properties
		setWidth("420px");
		setHeight("41px");
		
		// LabelVS
		LabelVS = new Label();
		LabelVS.setImmediate(false);
		LabelVS.setWidth("-1px");
		LabelVS.setHeight("-1px");
		LabelVS.setValue(":");
		mainLayout.addComponent(LabelVS, 1, 0);
		mainLayout.setComponentAlignment(LabelVS, new Alignment(48));
		
		return mainLayout;
	}

}
