package com.tipgame.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class HomeTeamView extends CustomComponent {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Embedded HomeTeamImage;
	@AutoGenerated
	private Label LabelHomeTeamName;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = -105656643577607173L;
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public HomeTeamView(String teamName, String imageSource) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		setHomeTeamView(teamName, imageSource);
	}
	
	private void setHomeTeamView(String teamName, String imageSource)
	{
		LabelHomeTeamName.setValue(teamName);
		// embedded_1
				HomeTeamImage = new Embedded();
				HomeTeamImage.setImmediate(false);
				HomeTeamImage.setWidth("40px");
				HomeTeamImage.setHeight("40px");
				HomeTeamImage.setSource(new ThemeResource(imageSource));
				HomeTeamImage.setType(1);
				HomeTeamImage.setMimeType("image/png");
				mainLayout.addComponent(HomeTeamImage, 1, 0);
				mainLayout.setComponentAlignment(HomeTeamImage, new Alignment(48));
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("140px");
		mainLayout.setHeight("40px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(2);
		
		// top-level component properties
		setWidth("140px");
		setHeight("40px");
		
		// LabelHomeTeamName
		LabelHomeTeamName = new Label();
		LabelHomeTeamName.setImmediate(false);
		LabelHomeTeamName.setWidth("-1px");
		LabelHomeTeamName.setHeight("-1px");
		LabelHomeTeamName.setValue("Heimteam");
		mainLayout.addComponent(LabelHomeTeamName, 0, 0);
		mainLayout.setComponentAlignment(LabelHomeTeamName, new Alignment(48));
		
		return mainLayout;
	}

}
