package com.tipgame.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class HomeTeamView extends CustomComponent {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Label LabelHomeTeamName;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = -105656643577607173L;
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public HomeTeamView(String teamName, String imageSource) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		setHomeTeamView(teamName, imageSource);
	}
	
	private void setHomeTeamView(String teamName, String imageSource)
	{
		LabelHomeTeamName.setValue(teamName);
		
		/*Embedded ImageHomeTeam = new Embedded();
		ImageHomeTeam.setImmediate(false);
		ImageHomeTeam.setWidth("100.0%");
		ImageHomeTeam.setHeight("100.0%");
		ImageHomeTeam.setSource(new ThemeResource(homeTeam.getImageFlag()));
		ImageHomeTeam.setType(1);
		ImageHomeTeam.setMimeType("image/png");
		mainLayout.addComponent(ImageHomeTeam, 1, 0);*/
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("180px");
		mainLayout.setHeight("36px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(2);
		
		// top-level component properties
		setWidth("180px");
		setHeight("36px");
		
		// LabelHomeTeamName
		LabelHomeTeamName = new Label();
		LabelHomeTeamName.setImmediate(false);
		LabelHomeTeamName.setWidth("-1px");
		LabelHomeTeamName.setHeight("-1px");
		LabelHomeTeamName.setValue("Heimteam");
		mainLayout.addComponent(LabelHomeTeamName, 0, 0);
		mainLayout.setComponentAlignment(LabelHomeTeamName, new Alignment(48));
		
		return mainLayout;
	}

}
