package com.tipgame.ui.Statistics;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class PositionOverviewView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = -1911393345738035319L;
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PositionOverviewView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		Embedded positionenUebersicht_1 = new Embedded();
		positionenUebersicht_1.setImmediate(false);
		positionenUebersicht_1.setWidth("100%");
		positionenUebersicht_1.setHeight("100%");
		positionenUebersicht_1.setSource(new ThemeResource(
				"resources/statistics/positionenUebersicht_1.png"));
		positionenUebersicht_1.setType(1);
		positionenUebersicht_1.setMimeType("image/png");

		Embedded positionenUebersicht_2 = new Embedded();
		positionenUebersicht_2.setImmediate(false);
		positionenUebersicht_2.setWidth("100%");
		positionenUebersicht_2.setHeight("100%");
		positionenUebersicht_2.setSource(new ThemeResource(
				"resources/statistics/positionenUebersicht_2.png"));
		positionenUebersicht_2.setType(1);
		positionenUebersicht_2.setMimeType("image/png");		
		
		Embedded positionenUebersicht_3 = new Embedded();
		positionenUebersicht_3.setImmediate(false);
		positionenUebersicht_3.setWidth("100%");
		positionenUebersicht_3.setHeight("100%");
		positionenUebersicht_3.setSource(new ThemeResource(
				"resources/statistics/positionenUebersicht_3.png"));
		positionenUebersicht_3.setType(1);
		positionenUebersicht_3.setMimeType("image/png");
		
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setSizeFull();
		panel_1.setScrollable(true);
		
		panel_1.addComponent(positionenUebersicht_1);
		panel_1.addComponent(positionenUebersicht_2);
		panel_1.addComponent(positionenUebersicht_3);
		
		mainLayout.addComponent(panel_1);
		
		return mainLayout;
	}

}
